name: Validate

on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    name: "hassfest"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master