name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'images/**'
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'images/**'
      - 'README.md'

jobs:
  validate:
    name: "hassfest"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master